# Based on https://github.com/travier/fedora-kinoite/blob/main/.github/workflows/fedora-kinoite.yml

name: "Build Fedora Kinoite image"

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: fedora-kinoite
  BASE_IMAGE: quay.io/fedora/fedora-kinoite:latest

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Override version label (org.opencontainers.image.version)'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sign-published-image:
    uses: ./.github/workflows/signing.yml
    secrets: inherit
    with:
      registry: ${{ env.REGISTRY }}