name: "Sign published container image"

on:
  workflow_call:

jobs:
  sign:
    runs-on: ubuntu-latest
    environment: cosign-signing
    steps:
      - name: Sign the published container image
        run: |
          echo ${COSIGN_PRIVATE_KEY}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.sigstore_private_key }}