name: "Sign published container image"

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string

jobs:
  sign:
    runs-on: ubuntu-latest
    environment: cosign-signing
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Login to Container Registry
        run: |
          cosign login ${REGISTRY%%/*} \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}
        env:
          REGISTRY: ${{ inputs.registry }}